# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.19 is version 41
loaderVersion="[41,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Dwight-Studio/Deepworld/issues"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false

[[mods]]
modId="deepworld"
version="0.2.0"
displayName="The Deep World"
updateJSONURL="http://pastebin.com/raw/8WPVG1iu"
displayURL="dwightstudio.fr/mc/deepworld (WIP)"
logoFile="logo.png"
credits="All the sound effects originate from the amazing Epidemic Sound library."
authors="Deleranax, WhiteRed & GamerMine"
description='''
      To make the nether go truly deep.\n§bThe Deep World§r is a mod that introduces a new intermediate dimension
      between the overworld and the nether to complexify the access to the latter.
      '''

[[dependencies.deepworld]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.deepworld]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
